name: CI

on: [push]

permissions:
  contents: write

jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-node@v3
        with:
            node-version: '18.x'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - run: |
          npm ci
          npm run build
          npm i -g wrangler
          export CLOUDFLARE_API_TOKEN=$"CF_API_TOKEN" wrangler deploy
          
